on-unmatched = "info"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.deadnix]
command = "deadnix"
options = ["--fail"]
includes = ["*.nix"]

[formatter.yaml]
command = "yamlfmt"
includes = ["*.yml", "*.yaml"]

[formatter.typos]
command = "typos"
includes = ["*"]
